spring:
  application:
    name: media

  datasource:
    url: jdbc:postgresql://103.75.182.249:5434/media
    username: postgres
    password: K59Ptl*100504
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: false
  
  main:
    lazy-initialization: true # Chỉ tải các Bean khi cần thiết, giúp giảm RAM lúc khởi động
    
  jmx:
    enabled: false # Tắt JMX (Java Management Extensions) vì không dùng tới

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: media-upload-worker
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.dts.media"

server:
  port: 8080
  tomcat:
    threads:
      max: 50 # Mặc định là 200, với VPS nhỏ chỉ cần 50 luồng là đủ

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    enabled: true
  instance:
    prefer-ip-address: true
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS:127.0.0.1}
